### PR TITLE
Fix Hauptbahnhof - Röthenbach scenario

### LINKED ISSUE #5: Collision in Plärrer
The player train should wait until 2:40 or something to let the other train out of the station.

### LINKED ISSUE #6: No wait time in Rothenburger Str.
There is no minimal waiting time set in Rothenburger Str. allowing to open and instantly closing the doors.

Edit: Same for Schweinau and Hohe Marter

### LINKED ISSUE #7: Passengers are entering in Röthenbach
Passengers are entering the train at Röthenbach despite being the last station

### PR DESCRIPTION
**Pull request by HaSa1002**
Fixes #7
Fixes #6
Fixes #5 by removing the two colliding trains

### CODE REVIEW

**Comment by HaSa1002** [comment]
@nalquas This PR should fix the routing errors you found in https://github.com/Libre-TrainSim/u2-nuremberg/pull/4#issuecomment-1242973492 (when used together with https://github.com/Libre-TrainSim/Libre-TrainSim/pull/454)

**Comment by nalquas** [comment]
Just tested the Hauptbahnhof-Röthenbach scenario. Video footage: https://youtu.be/yvIhi_LFRks

I noticed two issues:

- Directly after Opernhaus, we're slightly misrouted and almost crash into another train (around 02:00 in the video). It seems that we are going left one switch earlier than we're supposed to.
- Between St. Leonhard and Schweinau, there's an uncomfortably low signal. (around 06:50 in the video)

I'll test the other direction next.

**Comment by nalquas** [comment]
I've now also tested the Röthenbach-Hauptbahnhof direction. Everything works perfectly here!
Video footage: https://youtu.be/ZB5NgCmPXBc

**Comment by HaSa1002** [comment]
@nalquas I fixed the mentioned issues. In order to fix the signal height issues, please also update the the game branch. I pushed an update there, too. My remove old route baking PR turned out to be fix issues, I come across 😅

Thanks for testing :)

**Comment by nalquas** [comment]
> I fixed the mentioned issues. In order to fix the signal height issues, please also update the the game branch. I pushed an update there, too.

That broke something with the signals. Now, the first signal you drive across always results in a "You overran a red signal ... failed scenario" popup. Additonally, the log is now full of these messages:

```
[2022-12-31 16:08:45][VERBOSE](Null) Signal Signal registered at rail.
[2022-12-31 16:08:45][VERBOSE](Null) Signal Signal2 registered at rail.
[2022-12-31 16:08:45][VERBOSE](Null) Signal Signal3 registered at rail.
[2022-12-31 16:08:45][VERBOSE](Null) Signal Signal4 registered at rail.
[2022-12-31 16:08:45][VERBOSE](Null) Signal Signal5 registered at rail.
[2022-12-31 16:08:45][VERBOSE](Null) Signal Signal6 registered at rail.
[2022-12-31 16:08:45][VERBOSE](Null) Signal Signal7 registered at rail.
[2022-12-31 16:08:45][VERBOSE](Null) Signal Signal8 registered at rail.
[2022-12-31 16:08:45][VERBOSE](Null) Signal Signal9 registered at rail.
... (this goes on until Signal69)
```

Full log: [godot_2022-12-31_16.10.35.log](https://github.com/Libre-TrainSim/u2-nuremberg/files/10327545/godot_2022-12-31_16.10.35.log)

**Comment by HaSa1002** [comment]
> That broke something with the signals. Now, the first signal you drive across always results in a "You overran a red signal ... failed scenario" popup. Additonally, the log is now full of these messages:

Sorry... I changed stuff without thinking. This time it should be properly fixed on both branches. Can you please try again?

**Comment by nalquas** [comment]
> Sorry... I changed stuff without thinking. This time it should be properly fixed on both branches. Can you please try again?

Perfect, works fine now. Just tested Hauptbahnhof-Röthenbach and everything was perfect this time. Nice job!

One minor thing: At the very end (Röthenbach Abstellgleis), I got this error message in the log. It's probably a wrong sound effect line in the scenario's station settings or something. It doesn't crash the game though or anything.

```
[2023-01-01 21:26:03][INFO](Null) Sending Message: The next station is Röthenbach Abstellgeis. It is 200m away.
Loading resource: res://
ERROR: No loader found for resource: res://.
   at: _load (core/io/resource_loader.cpp:278) - Method failed. Returning: RES()
jAudioManager:  not found. Please give in a appropriate path beginning with res://
```

**Comment by HaSa1002** [comment]
Yeah the error is because it tries to load a sound file even if the path is empty. We should surpress this for now using a check and then take a look at this class. It has a very suspicious suffix `Manager`... Feel free to merge the PRs that are working

**Review by nalquas — APPROVED** [review]
Tested both route directions, lgtm.

**Pull request merged**
