### PR TITLE
Convert U2 to TSCN chunks

### PR DESCRIPTION
**Pull request by DasCapschen**
Converts the map to the new TSCN chunks.

- [x] convert chunks to tscn
- [x] convert degrees to radians
- [x] disable grass on chunks 
- [x] convert scenarios to new scenario system

### CODE REVIEW

**Comment by HaSa1002** [comment]
@nalquas This PR may be of your interest :)

**Comment by nalquas** [comment]
Cool, seems to work for me (via mod export, as I think it's intended?).

Some observations along Hauptbahnhof-Röthenbach:

"St. Leonhard" seems to be missing a wall:
| Screenshots      | Screenshots |
| ----------- | ----------- |
| Screenshot_20220828_143156      | Screenshot_20220828_143159       |

"Hohe Marter" *might* be missing a wall, except if this is intentional?:
Screenshot_20220828_143601

Something's wrong with the routing near Röthenbach as I arrive on the wrong platform (and, subsequently, I never "arrive" at the station and can't end the scenario):
| Screenshots      | Screenshots |
| ----------- | ----------- |
| Screenshot_20220828_143718      | Screenshot_20220828_143841       |

**Comment by DasCapschen** [comment]
Can you try again @nalquas ?
I added the missing walls and I think the route should be fixed as well now.

**Comment by nalquas** [comment]
> Can you try again @nalquas ? I added the missing walls and I think the route should be fixed as well now.

I re-exported the map and tested both directions. I'm still having issues, although the missing walls are there now. They mainly seem to be routing-related.

### Hauptbahnhof-Röthenbach

Something is very broken with the routing here. One of the signals before Plärrer keeps showing red, so you can't pass. Investigating it further (by freecam-ing further along the track) I can see the following: The first train in front of me is waiting in the station (Plärrer) despite the signal being green. Then, there's another train stuck in the tunnel between Plärrer and Rothenburger Straße waiting on a red signal. Lastly, looking at Rothenburger Straße, there's not actually any train here.

| Screenshots      | Screenshots |
| ----------- | ----------- |
| Screenshot_20220911_152623  | Screenshot_20220911_152753   |
| Screenshot_20220911_152926 | Screenshot_20220911_152946 |

### Röthenbach-Hauptbahnhof

At the very first station, passengers seem to ignore the train and never enter. As a side note, you can also see that the doors animations of the Grey train are seemingly broken (they never visually open/close). Furthermore, when driving past the station (Röthenbach), the station list isn't updated (plus the distance to the next station seems... wrong?).

| Screenshots      | Screenshots |
| ----------- | ----------- |
| Screenshot_20220911_153125 | Screenshot_20220911_153201  |

The station list starts getting updated again once we reach Hohe Marter.

Aha, look at this, the route error has been detected somewhere in the log! Maybe this is of help?

```
[2022-09-11 15:32:52][ERROR](Player:[Spatial:114944]) Route incorrect! Reached station HoheMarter1 but the next_station should be Röthenbach1.
ERROR: (Player:[Spatial:114944]) Route incorrect! Reached station HoheMarter1 but the next_station should be Röthenbach1.
   at: call (modules/gdscript/gdscript_functions.cpp:775) - (Player:[Spatial:114944]) Route incorrect! Reached station HoheMarter1 but the next_station should be Röthenbach1.
```

Looking at the log there are quite a few script errors being thrown after this too, mainly the following two repeating over and over again:

```
SCRIPT ERROR: Invalid get index 'RothenburgerStraße1' (on base: 'Dictionary').
   at: LTSPlayer.get_distance_to_signal (res://Data/Scripts/Player.gdc:1245) - Invalid get index 'RothenburgerStraße1' (on base: 'Dictionary').
SCRIPT ERROR: Invalid operands 'Nil' and 'int' in operator '+'.
   at: LTSPlayer.updateNextStation (res://Data/Scripts/Player.gdc:1452) - Invalid operands 'Nil' and 'int' in operator '+'.
```

When approaching Rothenburger Straße, the routing gets out of hand and we're directed onto the wrong track, stopping us from driving further:

| Screenshots      | Screenshots |
| ----------- | ----------- |
| Screenshot_20220911_153544  | Screenshot_20220911_153555    | 

Here's some relevant log regarding the door animation issue (for which we should create a separate issue in the main repo):
```
ERROR: (Node not found: "Doors/DoorR12:translation" (relative to "/root/World/Players/DriverCabinF/Doors").)
   at: get_node (scene/main/node.cpp:1465) - Method failed. Returning: nullptr
ERROR: On Animation: 'open', couldn't resolve track:  'Doors/DoorR12:translation'.
   at: _ensure_node_caches (scene/animation/animation_player.cpp:251) - Condition "!child" is true. Continuing.
ERROR: (Node not found: "Doors/DoorR11:translation" (relative to "/root/World/Players/DriverCabinF/Doors").)
   at: get_node (scene/main/node.cpp:1465) - Method failed. Returning: nullptr
ERROR: On Animation: 'open', couldn't resolve track:  'Doors/DoorR11:translation'.
   at: _ensure_node_caches (scene/animation/animation_player.cpp:251) - Condition "!child" is true. Continuing.
ERROR: (Node not found: "Doors/DoorR10:translation" (relative to "/root/World/Players/DriverCabinF/Doors").)
   at: get_node (scene/main/node.cpp:1465) - Method failed. Returning: nullptr
ERROR: On Animation: 'open', couldn't resolve track:  'Doors/DoorR10:translation'.
   at: _ensure_node_caches (scene/animation/animation_player.cpp:251) - Condition "!child" is true. Continuing.
ERROR: (Node not found: "Doors/DoorR9:translation" (relative to "/root/World/Players/DriverCabinF/Doors").)
   at: get_node (scene/main/node.cpp:1465) - Method failed. Returning: nullptr
ERROR: On Animation: 'open', couldn't resolve track:  'Doors/DoorR9:translation'.
   at: _ensure_node_caches (scene/animation/animation_player.cpp:251) - Condition "!child" is true. Continuing.
ERROR: (Node not found: "Doors/DoorR8:translation" (relative to "/root/World/Players/DriverCabinF/Doors").)
   at: get_node (scene/main/node.cpp:1465) - Method failed. Returning: nullptr
ERROR: On Animation: 'open', couldn't resolve track:  'Doors/DoorR8:translation'.
   at: _ensure_node_caches (scene/animation/animation_player.cpp:251) - Condition "!child" is true. Continuing.
ERROR: (Node not found: "Doors/DoorR7:translation" (relative to "/root/World/Players/DriverCabinF/Doors").)
   at: get_node (scene/main/node.cpp:1465) - Method failed. Returning: nullptr
(and so on, the errors continue for a few hundred lines...)
```

### Minor Issues

Neither of the scenarios has a description, so the text box at the start looks very empty.
Screenshot_20220911_152408

### Other

If you need the entire log (I tested both track directions in one go), I've attached it: [godot.log](https://github.com/Libre-TrainSim/u2-nuremberg/files/9542705/godot.log)

**Review by HaSa1002 — APPROVED** [review]
lgtm

**Comment by HaSa1002** [comment]
Descriptions seems to be a different issue

**Pull request merged**
