### PR TITLE
Convert to 1000m chunks

### PR DESCRIPTION
**Pull request by HaSa1002**
Conversion done as an example for https://github.com/Libre-TrainSim/Libre-TrainSim/pull/452

### CODE REVIEW

**Comment by HaSa1002** [comment]
Video: https://youtu.be/SQfjWXMiTqE

**Comment by HaSa1002** [comment]
Should be working now

**Comment by nalquas** [comment]
I think we can merge this now, as it's working fine and https://github.com/Libre-TrainSim/Libre-TrainSim/pull/452 has been merged.

**Review by nalquas — APPROVED** [review]
Lgtm!

**Pull request merged**
